# Generated by Django 3.1.1 on 2020-10-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywikigame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='source',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='target',
            field=models.TextField(null=True),
        ),
    ]
